In [ ]:
#importing all libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
BASE_PATH = '/content/drive/MyDrive/Instacart Kaggle/'

In [ ]:
# reading all the files from instacart folder
orders = pd.read_csv(BASE_PATH + 'orders.csv')
aisles = pd.read_csv(BASE_PATH + 'aisles.csv')
departments = pd.read_csv(BASE_PATH + 'departments.csv')
order_products_prior = pd.read_csv(BASE_PATH + 'order_products__prior.csv')
order_products_train = pd.read_csv(BASE_PATH + 'order_products__train.csv')
products = pd.read_csv(BASE_PATH + 'products.csv')

In [ ]:
# head function shows what are the contents in the csv
orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [ ]:
# shape function shows how many rows and columns exist in the csv
orders.shape

(3421083, 7)

In [ ]:
# printing the details of csv to confirm if all the data loaded properly
print("orders:", orders.shape)
print("aisles:", aisles.shape)
print("departments:", departments.shape)
print("order_products_prior:", order_products_prior.shape)
print("order_products_train:", order_products_train.shape)
print("products:", products.shape)

orders: (3421083, 7)
aisles: (134, 2)
departments: (21, 2)
order_products_prior: (32434489, 4)
order_products_train: (1384617, 4)
products: (49688, 4)

In [ ]:
# Get summary information for each dataframe - column names, data types, and null counts
orders.info()
aisles.info()
departments.info()
order_products_prior.info()
order_products_train.info()
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3421083 entries, 0 to 3421082
Data columns (total 7 columns):
 #   Column                  Dtype
---  ------                  -----
 0   order_id                int64
 1   user_id                 int64
 2   eval_set                object
 3   order_number            int64
 4   order_dow               int64
 5   order_hour_of_day       int64
 6   days_since_prior_order  float64
dtypes: float64(1), int64(5), object(1)
memory usage: 182.7+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 134 entries, 0 to 133
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   aisle_id  134 non-null    int64
 1   aisle     134 non-null    object
dtypes: int64(1), object(1)
memory usage: 2.2+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   department_id  21 non-null     int64
 1   department     21 non-null     object
dtypes: int64(1), object(1)
memory usage: 468.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32434489 entries, 0 to 32434488
Data columns (total 4 columns):
 #   Column             Dtype
---  ------             -----
 0   order_id           int64
 1   product_id         int64
 2   add_to_cart_order  int64
 3   reordered          int64
dtypes: int64(4)
memory usage: 989.8 MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1384617 entries, 0 to 1384616
Data columns (total 4 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   order_id           1384617 non-null  int64
 1   product_id         1384617 non-null  int64
 2   add_to_cart_order  1384617 non-null  int64
 3   reordered          1384617 non-null  int64
dtypes: int64(4)
memory usage: 42.3 MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49688 entries, 0 to 49687
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     49688 non-null  int64
 1   product_name   49688 non-null  object
 2   aisle_id       49688 non-null  int64
 3   department_id  49688 non-null  int64
dtypes: int64(3), object(1)
memory usage: 1.5+ MB

In [ ]:
# Check for null values across all 6 tables before cleaning
print("orders:",orders.isnull().sum())
print("aisles:",aisles.isnull().sum())
print("departments:",departments.isnull().sum())
print("order_products_prior:",order_products_prior.isnull().sum())
print("order_products_train:",order_products_train.isnull().sum())
print("products:",products.isnull().sum())

orders: order_id                       0
user_id                        0
eval_set                       0
order_number                   0
order_dow                      0
order_hour_of_day              0
days_since_prior_order    206209
dtype: int64
aisles: aisle_id    0
aisle       0
dtype: int64
departments: department_id    0
department       0
dtype: int64
order_products_prior: order_id             0
product_id           0
add_to_cart_order    0
reordered            0
dtype: int64
order_products_train: order_id             0
product_id           0
add_to_cart_order    0
reordered            0
dtype: int64
products: product_id       0
product_name     0
aisle_id         0
department_id    0
dtype: int64

In [ ]:
# Check for duplicate rows across all 6 tables
print("orders:",orders.duplicated().sum())
print("aisles:",aisles.duplicated().sum())
print("departments:",departments.duplicated().sum())
print("order_products_prior:",order_products_prior.duplicated().sum())
print("order_products_train:",order_products_train.duplicated().sum())
print("products:",products.duplicated().sum())

orders: 0
aisles: 0
departments: 0
order_products_prior: 0
order_products_train: 0
products: 0

In [ ]:
# Checking the data inside the column to see whats relavant or if anything needs to be filtered out
orders['eval_set'].value_counts()

eval_set
prior    3214874
train     131209
test       75000
Name: count, dtype: int64

In [ ]:
# Filtering out unwanted data from the column eval_set
orders_filtered = orders[orders['eval_set'].isin(['prior', 'train'])]

In [ ]:
# Checking the new dataframe with filtered data
orders_filtered['eval_set'].value_counts()

eval_set
prior    3214874
train     131209
Name: count, dtype: int64

In [ ]:
orders_filtered.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [ ]:
order_products_prior.head()

   order_id  product_id  add_to_cart_order  reordered
0         2       33120                  1          1
1         2       28985                  2          1
2         2        9327                  3          0
3         2       45918                  4          1
4         2       30035                  5          0

In [ ]:
# Merge order-product-prior data with order details using order_id as the key
orders_products_merged = pd.merge(order_products_prior, orders_filtered, on='order_id')
print("orders_products_merged:", orders_products_merged.shape)

orders_products_merged: (32434489, 10)

In [ ]:
# Merge order-product-train data with order details using order_id as the key
orders_products_train_merged = pd.merge(order_products_train, orders_filtered, on='order_id')
print("orders_products_train_merged:", orders_products_train_merged.shape)

orders_products_train_merged: (1384617, 10)

In [ ]:
# Stack prior and train order-product tables into one master table
all_order_products = pd.concat([orders_products_merged, orders_products_train_merged])
print("all_order_products:", all_order_products.shape)

all_order_products: (33819106, 10)

In [ ]:
products.head()

,product_id,product_name,aisle_id,department_id
0,1,Chocolate Sandwich Cookies,61,19
1,2,All-Seasons Salt,104,13
2,3,Robust Golden Unsweetened Oolong Tea,94,7
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1
4,5,Green Chile Anytime Sauce,5,13

In [ ]:
aisles.head()

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

In [ ]:
departments.head()

   department_id department
0              1     frozen
1              2      other
2              3     bakery
3              4    produce
4              5    alcohol

In [ ]:
# Enrich products table with aisle and department names
products_enriched = pd.merge(products, aisles, on='aisle_id')
products_enriched = pd.merge(products_enriched, departments, on='department_id')
print("products_enriched:", products_enriched.shape)

products_enriched: (49688, 6)

In [ ]:
products_enriched.head()

,product_id,product_name,aisle_id,department_id,aisle,department
0,1,Chocolate Sandwich Cookies,61,19,cookies cakes,snacks
1,2,All-Seasons Salt,104,13,spices seasonings,pantry
2,3,Robust Golden Unsweetened Oolong Tea,94,7,tea,beverages
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,frozen meals,frozen
4,5,Green Chile Anytime Sauce,5,13,marinades meat preparation,pantry

In [ ]:
all_order_products.head()

,order_id,product_id,add_to_cart_order,reordered,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2,33120,1,1,202279,prior,3,5,9,8.0
1,2,28985,2,1,202279,prior,3,5,9,8.0
2,2,9327,3,0,202279,prior,3,5,9,8.0
3,2,45918,4,1,202279,prior,3,5,9,8.0
4,2,30035,5,0,202279,prior,3,5,9,8.0

In [ ]:
# Final master table combining all order-product data with product, aisle, and department details
master = pd.merge(all_order_products, products_enriched, on='product_id')
print("master:", master.shape)

master: (33819106, 15)

In [ ]:
master.head()

,order_id,product_id,add_to_cart_order,reordered,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_name,aisle_id,department_id,aisle,department
0,2,33120,1,1,202279,prior,3,5,9,8.0,Organic Egg Whites,86,16,eggs,dairy eggs
1,2,28985,2,1,202279,prior,3,5,9,8.0,Michigan Organic Kale,83,4,fresh vegetables,produce
2,2,9327,3,0,202279,prior,3,5,9,8.0,Garlic Powder,104,13,spices seasonings,pantry
3,2,45918,4,1,202279,prior,3,5,9,8.0,Coconut Butter,19,13,oils vinegars,pantry
4,2,30035,5,0,202279,prior,3,5,9,8.0,Natural Sweetener,17,13,baking ingredients,pantry

In [ ]:
# Aggregate order history to one row per customer
customer_summary = (
    orders_filtered
    .groupby('user_id')
    .agg(
        total_orders     = ('order_number', 'max'),
        avg_days_between = ('days_since_prior_order', 'mean'),
        std_days_between = ('days_since_prior_order', 'std'),
        max_gap          = ('days_since_prior_order', 'max')
    )
    .reset_index()
)
print("customer_summary:", customer_summary.shape)

customer_summary: (206209, 5)

In [ ]:
customer_summary.head()

   user_id  total_orders  avg_days_between  std_days_between  max_gap
0        1            11         19.000000          9.030811     30.0
1        2            15         16.285714         10.268912     30.0
2        3            12         12.090909          5.375026     21.0
3        4             5         13.750000          9.500000     21.0
4        5             5         11.500000          5.446712     19.0

In [ ]:
# Fill NaN std with 0 — customers with only 1 order have no variability
customer_summary['std_days_between'] = customer_summary['std_days_between'].fillna(0)

In [ ]:
# Checking for nulls
print(customer_summary.isnull().sum())

user_id             0
total_orders        0
avg_days_between    0
std_days_between    0
max_gap             0
dtype: int64

In [ ]:
import os
os.makedirs(BASE_PATH + 'cleaned', exist_ok=True)

In [ ]:
# Save cleaned files to Drive so we don't have to reload raw data every session
customer_summary.to_csv(BASE_PATH + 'cleaned/customer_summary.csv', index=False)
orders_filtered.to_csv(BASE_PATH + 'cleaned/orders_clean.csv', index=False)
products_enriched.to_csv(BASE_PATH + 'cleaned/products_enriched.csv', index=False)

In [ ]:
# Save a 500K row sample of master for Snowflake upload
master.sample(500_000, random_state=42).to_csv(BASE_PATH + 'cleaned/master_sample.csv', index=False)